services:
  catalogue:
    build:
      dockerfile: catalogue.Dockerfile
    image: kgc11/catalogue:1.0.0
    container_name: catalogue
    depends_on:
    - mongodb

services:
  mongodb:
    build:
      dockerfile: mongodb.Dockerfile     # It moves to mongodb directory
    image: kgc11/mongodb:1.0.0    # docker build -t kgc11/momgodb:1.0.0
    container_nmae: mongodb


networks:
  default:
    driver: bridge
    name: roboshop
    external: false    # if true, you need to create network manually